

spring:
  application:
    name: SpringBootDasar
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: Password1
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show_sql: true
    generate-ddl: true

server:
  address: 172.20.1.96
  port: 8090
